name: Deploy To AWS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install flak8
        run: |
          pip install flake8

      - name: Run linter
        run: |
          flake8 lambda
          
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        run: terraform fmt
        continue-on-error: true
        working-directory: ./terraform

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -no-color
        continue-on-error: true
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -no-color -auto-approve
        continue-on-error: true
        working-directory: ./terraform