name: Deploy to AWS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup python
        uses: actions@setup-python@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install flake8
        run: |
          python -m pip install --upgade pip
          pip install flake8

      - name: Run lint
        run: |
          flake8 lambda

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        run: terraform fmt
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform apply
        run: terraform apply -auto-approve -no-color